Diego user creation
inso-education/inso-api pull request #8
Opened 2022-07-01 19:09 UTC by dsoto18

Contact patch functionality requires finishing up

2022-07-05 17:48 UTC, pzalep1 commented on src/entities/user/edit-user.ts
> +    //     description: 'The ObjectId of the user being edited',
If this isn't used you can delete this.

2022-07-05 17:49 UTC, pzalep1 commented on src/modules/user/user.controller.ts
> +      'first name': foundUser.f_name,
The return user should be of type UserReadDTO

2022-07-05 17:50 UTC, pzalep1 commented on src/modules/user/user.controller.ts
> +      'last name': foundUser.l_name,
Spaces shouldn't be in json keys because they are harder to parse.

2022-07-05 17:50 UTC, pzalep1 commented on src/modules/user/user.controller.ts
> +    const SameUsername = await this.userModel.findOne({username: user.username})
Camelcase variables.

2022-07-05 17:50 UTC, pzalep1 commented on src/modules/user/user.controller.ts
> +    ValidateUsername(user.username);
Camelcase function names

2022-07-05 17:51 UTC, pzalep1 commented on src/modules/user/user.controller.ts
> +    }
This can be simplified using the javascript .filter function: https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Array/filter

2022-07-05 17:52 UTC, pzalep1 commented on src/modules/user/user.controller.ts
> +      }
This can be simplified using the javascript map function: https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Array/map

2022-07-05 17:56 UTC, pzalep1 commented on src/modules/user/user.controller.ts
> +                        '?', '/', ';', ':', '-', '=', '+', '|', '`', '~', ',', '.', '[', ']'];
Read this article on how to use regex to perform these checks: https://www.section.io/engineering-education/password-strength-checker-javascript/

2022-07-05 18:15 UTC, dsoto18 commented on src/entities/user/create-user.ts
> +    public verified: boolean
Right now it is optional and works as I described dateJoined, it is part of the DTO but can be left out of the request bodies, if they are still included they get overwritten anyways. If you prefer I take them out completely though then sure I can do that.

2022-07-05 18:15 UTC, dsoto18 commented on src/entities/user/create-user.ts
> +        required: true,
Description added.

2022-07-05 18:15 UTC, dsoto18 commented on src/entities/user/create-user.ts
> +    @ValidateNested()
Suggested change was made.

2022-07-05 18:18 UTC, dsoto18 commented on src/entities/user/create-user.ts
> +        required: true,
Description added.

2022-07-05 18:21 UTC, dsoto18 commented on src/entities/user/create-user.ts
> +        required: true,
Description added.

2022-07-05 18:21 UTC, dsoto18 commented on src/entities/user/create-user.ts
> +        required: true,
Description added.

2022-07-05 18:38 UTC, dsoto18 commented on src/modules/user/user.controller.ts
> +      'last name': foundUser.l_name,
Yes I understand what you mean, it has been changed.

2022-07-06 13:13 UTC, dsoto18 commented on src/modules/user/user.controller.ts
> +    const SameUsername = await this.userModel.findOne({username: user.username})
Done.

2022-07-06 13:14 UTC, dsoto18 commented on src/modules/user/user.controller.ts
> +    ValidatePassword(user.password);
Done.

2022-07-06 15:06 UTC, dsoto18 commented on src/modules/user/user.controller.ts
> +    }
Thanks for the suggestion, I made a hasDuplicateContacts function which uses the filter function, code works and looks cleaner now.

2022-07-12 02:31 UTC, pzalep1 requested changes

2022-07-12 02:31 UTC, pzalep1 commented on src/entities/user/create-user.ts
> +        name: 'verified',
Can you add descriptions to these too?

2022-07-12 02:31 UTC, pzalep1 commented on src/entities/user/edit-user.ts
> +    //     required: false,
If this isn't used can you remove this?

2022-07-12 02:31 UTC, pzalep1 commented on src/entities/user/read-user.ts
> +    // contact: [
If this isn't used can we remove it?

2022-07-12 02:31 UTC, pzalep1 commented on src/entities/user/user.ts
> +    // @Prop(Boolean)
If this isn't used can you remove this?

2022-07-12 02:31 UTC, pzalep1 commented on src/modules/user/user.controller.ts
> +    const returnUser: UserReadDTO = {
You should be able to just pass this through the UserReadDTO constructor

2022-07-12 02:31 UTC, pzalep1 commented on src/modules/user/user.controller.ts
> +  @ApiBody({description: '', type: UserCreateDTO})
Can you add a description here?

2022-07-12 02:31 UTC, pzalep1 commented on src/modules/user/user.controller.ts
> +     if(isEmail(user.contact[i].email) == false ){
I would check to see if there is an isEmail in class validator

2022-07-12 02:31 UTC, pzalep1 commented on src/modules/user/user.controller.ts
> +  @ApiBody({description: '', type: UserEditDTO})
Can you add a description here?

2022-07-12 02:31 UTC, pzalep1 commented on src/modules/user/user.controller.ts
> +        if(isEmail(user.contact[i].email) == false ){ throw new HttpException('Email: ' + user.contact[i].email + ', is not a valid email address', HttpStatus.BAD_REQUEST)};
Can you add new lines for these if statements to make them more readable?

2022-07-12 02:31 UTC, pzalep1 commented on src/modules/user/user.controller.ts
> +      for(var i = 0; i < user.contact.length; i++){
You can use a for await here

2022-07-12 02:31 UTC, pzalep1 commented on src/modules/user/user.controller.ts
> +      // for(var d = 0; d < user.contact.length; d++){
If this isn't being used it can be removed

2022-07-12 02:31 UTC, pzalep1 commented on src/modules/user/user.controller.ts
> +      if(user.sso.length == 0){throw new HttpException('Array length for SSO cannot be 0', HttpStatus.BAD_REQUEST)};
This can probably be handled in the class-validator checks in the DTOs

2022-07-12 02:31 UTC, pzalep1 commented on src/modules/user/user.controller.ts
> +function validateUsername( userName: string){
Can you add block comments to these functions?

2022-07-12 02:31 UTC, pzalep1 commented on src/modules/user/user.controller.ts
> +  if(checkStrength == false){ throw new HttpException('Password must contain at least one lowercase character', HttpStatus.BAD_REQUEST)};
Can you add new lines to these if statements for readability?

2022-07-12 13:20 UTC, dsoto18 commented on src/entities/user/read-user.ts
> +    // contact: [
It has been removed.

2022-07-12 13:47 UTC, dsoto18 commented on src/modules/user/user.controller.ts
> +  @ApiBody({description: '', type: UserCreateDTO})
Yes, it is added.

2022-07-12 13:49 UTC, dsoto18 commented on src/modules/user/user.controller.ts
> +  @ApiBody({description: '', type: UserEditDTO})
It has been added.

2022-07-12 13:59 UTC, dsoto18 commented on src/modules/user/user.controller.ts
> +  if(checkStrength == false){ throw new HttpException('Password must contain at least one lowercase character', HttpStatus.BAD_REQUEST)};
Yes, there's now spaces in between each small block of code, that should help more.

2022-07-12 14:08 UTC, dsoto18 commented on src/modules/user/user.controller.ts
> +function validateUsername( userName: string){
I've now added comments before each function to describe the purpose of each.

2022-07-12 14:12 UTC, dsoto18 commented on src/modules/user/user.controller.ts
> +      if(user.sso.length == 0){throw new HttpException('Array length for SSO cannot be 0', HttpStatus.BAD_REQUEST)};
Yes you're right, just made the change to the DTO and removed these lines.

2022-07-12 17:37 UTC, dsoto18 commented on src/modules/user/user.controller.ts
> +      // for(var d = 0; d < user.contact.length; d++){
It is removed.

2022-07-12 17:38 UTC, dsoto18 commented on src/entities/user/edit-user.ts
> +    //     required: false,
It is now being used, it's left in an uncommented.

2022-07-12 17:39 UTC, dsoto18 commented on src/entities/user/user.ts
> +    // @Prop(Boolean)
It's now being used, it is left in and now uncommented out.

2022-07-12 17:40 UTC, dsoto18 commented on src/modules/user/user.controller.ts
> +     if(isEmail(user.contact[i].email) == false ){
There is one, now using it to validate in DTOs, but the isEmail function in the code is still needed to check that the username is not an email.

2022-07-12 18:04 UTC, dsoto18 commented on src/modules/user/user.controller.ts
> +      for(var i = 0; i < user.contact.length; i++){
Got it working with the for await now, thanks for the suggestion.

2022-07-13 03:10 UTC, pzalep1 commented on src/entities/user/edit-user.ts
> +        description: 'The users level of authorization',
```suggestion
        description: 'The users level of education',
```

2022-07-13 03:10 UTC, pzalep1 commented on src/entities/user/read-user.ts
> +        //Object.assign(this, partial);
Does this not work for this class?

2022-07-13 03:10 UTC, pzalep1 commented on src/modules/user/user.controller.ts
> +    if(!Types.ObjectId.isValid(userId)){ throw new HttpException("User id is not valid", HttpStatus.BAD_REQUEST) }
Can you put these if statements on new lines for readability?

2022-07-13 03:10 UTC, pzalep1 commented on src/modules/user/user.controller.ts
> +//////// uses regex to ensure a string is a valid email address ////////
Let's use a JSDoc format instead: https://jsdoc.app/about-getting-started.html

2022-07-13 03:10 UTC, pzalep1 commented on src/modules/user/user.controller.ts
> +function removeUnwantedContacts(array: ContactEditDTO[], oldArray: Contact[]){
This function can be simplified to just filter out the contacts to delete and then return that array to overwrite the existing one in the db.

2022-07-13 13:13 UTC, dsoto18 commented on src/entities/user/edit-user.ts
> +        description: 'The users level of authorization',
Thanks, the suggested change was made.

2022-07-13 13:19 UTC, dsoto18 commented on src/entities/user/read-user.ts
> +        //Object.assign(this, partial);
When using the Object.assign line the UserReadDTO would not look the way its supposed to, it would create a large JSON object with information we don't need, also it returned the password and SSO which is wrong.

2022-07-13 13:24 UTC, dsoto18 commented on src/modules/user/user.controller.ts
> +    if(!Types.ObjectId.isValid(userId)){ throw new HttpException("User id is not valid", HttpStatus.BAD_REQUEST) }
Sure, just fixed it.

2022-07-13 13:32 UTC, dsoto18 commented on src/modules/user/user.controller.ts
> +//////// uses regex to ensure a string is a valid email address ////////
Thanks, the comments are now formatted the right way.

2022-07-13 13:47 UTC, dsoto18 commented on src/modules/user/user.controller.ts
> +function removeUnwantedContacts(array: ContactEditDTO[], oldArray: Contact[]){
If that overwrites the existing one in the db, then it would also remove the existing contacts they would want to keep I'm pretty sure. Or maybe I don't understand exactly what you mean.

2022-07-17 12:34 UTC, pzalep1 reviewed
Looking good, just a few comments!

2022-07-17 12:34 UTC, pzalep1 commented on src/auth/auth.service.ts
> +            console.log('password validated!');
We should check if the match is false and throw a 400 error.

2022-07-17 12:34 UTC, pzalep1 commented on src/auth/auth.service.ts
> +        const user = await this.userController.returnUser(username);
We should use the email instead of the username login. People don't remember usernames but they remember their emails

2022-07-19 13:53 UTC, dsoto18 commented on src/auth/auth.service.ts
> +            console.log('password validated!');
Right, just set that up now. Thanks

2022-07-19 13:59 UTC, dsoto18 commented on src/auth/auth.service.ts
> +        const user = await this.userController.returnUser(username);
That sounds better, just made the change.

2022-07-26 02:49 UTC, merged